# Generated by Django 4.1.3 on 2023-07-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cedula_persona', models.CharField(max_length=30, null=True)),
                ('nombres_persona', models.CharField(max_length=30, null=True)),
                ('apellidos_persona', models.CharField(max_length=30, null=True)),
                ('telefono_persona', models.CharField(max_length=30, null=True)),
                ('email_usuario', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('texto', models.TextField(null=True)),
                ('rol_usuario', models.CharField(choices=[('user', 'user'), ('admin', 'admin')], max_length=13)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
